### ISSUE TITLE
Peer code review

### ISSUE THREAD

**Issue by Nicolaswg** [lisandroseia/Portfolio#8]
# Code review 🦅 

### Recommendations:

- Used the transition properties for a better CSS clean code (hover effect) 👍

**Comment by Yothu** [comment]
- I would recommend changing the name of the class `framework` because the text in the elements where the class is used are not frameworks but languages.
- I would also recommend changing the `alt` attribute value of the social media icons from just the name of the social media to "social media"-logo, for example, `twitter-logo`.
